\set ON_ERROR_STOP on
begin;
create function pg_temp.assert_true(v boolean,label text) returns void language plpgsql as $$ begin if v is not true then raise exception 'ASSERTION FAILED: %',label;end if;end $$;
create function pg_temp.expect_error(statement text,expected text) returns void language plpgsql as $$ begin begin execute statement;exception when others then if position(expected in sqlerrm)>0 then return;else raise exception 'Expected %, got %',expected,sqlerrm;end if;end;raise exception 'Expected error %',expected;end $$;
insert into auth.users(id,email,aud,role) values('d4444444-4444-4444-8444-444444444444','lesson@example.invalid','authenticated','authenticated'),('e5555555-5555-4555-8555-555555555555','stranger@example.invalid','authenticated','authenticated');
insert into english_private.app_owner(owner_id) values('d4444444-4444-4444-8444-444444444444');
select set_config('request.jwt.claim.sub','d4444444-4444-4444-8444-444444444444',true);
insert into english_private.phrases(id,owner_id,legacy_phrase_id,chunk,cue_zh,status,review_stage,next_review_at,topic,natural_example)
select ('f0000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'d4444444-4444-4444-8444-444444444444','v3-'||i,case i when 1 then 'grab a coffee' when 2 then 'cut back on' when 3 then 'run as scheduled' else 'test expression '||i end,'表达意思 '||i,case when i<=2 then 'mastered' when i=9 then 'suspended' else 'active' end,3,now()-interval '1 day',case when i<=2 then 'daily life' else 'work' end,'A natural example.' from generate_series(1,9)i;
-- Persisted difficulty leads to a supported gap, not a full-recall success.
insert into english_private.review_events(owner_id,phrase_id,prompt,user_answer,result,question_type,affects_srs,rule_version,learning_date,target_outcome,hint_used,metadata)
select owner_id,id,'previous prompt','wrong','forgotten','whole_recall',false,'english_v3',english_private.learning_date()-1,'forgotten',false,'{"phase":"review"}' from english_private.phrases where legacy_phrase_id='v3-3';
create temp table st(k text primary key,v jsonb);
insert into st values('boot',english_api.get_review_bootstrap());
select pg_temp.assert_true((select v->>'ruleVersion'='english_v3' and v->'settings'->>'defaultQuestionCount'='8' and v->>'actualCount'='8' from st where k='boot'),'default 8, mastered included, suspended excluded');
select pg_temp.assert_true((select count(*)=2 from english_private.daily_queue_items i join english_private.phrases p on p.id=i.phrase_id where p.status='mastered'),'mastered due included');
insert into st values('job',english_api.create_ai_job('question_prepare',null,(select(v->>'queueId')::uuid from st where k='boot'),'prepare-v3'));
select pg_temp.assert_true((select v->>'expectedCount'='10' from st where k='job'),'8 review plus exactly 2 expression');
select pg_temp.assert_true((select count(*)=2 from english_private.ai_jobs j,jsonb_array_elements(j.input_snapshot->'items')x where x->>'questionType'='post_reading_expression'),'expression without success gate');
select pg_temp.assert_true((english_api.get_ai_job_prompt((select(v->>'jobId')::uuid from st where k='job'))->>'prompt') like '%120–180%','complete frozen material contract');
insert into st values('prompt',english_api.get_ai_job_prompt((select(v->>'jobId')::uuid from st where k='job')));
select pg_temp.assert_true((select jsonb_array_length(v->'outputContract'->'items')=10 and jsonb_typeof(v->'outputContract'->'material')='object' from st where k='prompt'),'single example includes the complete lesson and all questions');
select pg_temp.assert_true((select not exists(select 1 from jsonb_array_elements(v->'snapshot'->'items')s left join jsonb_array_elements(v->'outputContract'->'items')x on x->'position'=s->'position' where x->'queueItemId' is distinct from s->'queueItemId' or x->'questionType' is distinct from s->'questionType' or x->'phase' is distinct from s->'phase' or x->'answerForm' is distinct from s->'answerForm') from st where k='prompt'),'question example echoes every frozen identity and phase');
select pg_temp.assert_true((select v->'outputContract'->'material'->'targetPhraseIds'=v->'snapshot'->'targetPhraseIds' and jsonb_array_length(v->'outputContract'->'material'->'notes')=jsonb_array_length(v->'snapshot'->'targetPhraseIds') from st where k='prompt'),'material example includes each frozen target');
select pg_temp.assert_true((select split_part(split_part(v->>'prompt',E'JSON合同示例（替换占位内容，原样回显标识符）：\n',2),E'\n冻结输入 snapshot：\n',1)::jsonb=v->'outputContract' and strpos(v->>'prompt','附加顶层字段')=0 from st where k='prompt'),'displayed example is one complete parseable contract');
insert into st select 'payload',jsonb_build_object('jobId',j.id,'batchId',j.batch_id,'snapshotHash',j.snapshot_hash,'ruleVersion','english_v3','modelId','contract-test',
 'material',jsonb_build_object('title','A short conversation','kind','dialogue','body',trim(repeat('We are discussing a simple plan for this afternoon. ',15)),'explanationZh','讨论下午的计划','targetPhraseIds',j.input_snapshot->'targetPhraseIds','notes',(select jsonb_agg(jsonb_build_object('phraseId',x,'explanationZh','适合日常交流')) from jsonb_array_elements_text(j.input_snapshot->'targetPhraseIds')x)),
 'items',(select jsonb_agg(jsonb_build_object('queueItemId',x->>'queueItemId','position',x->'position','questionType',x->>'questionType','phase',x->>'phase','answerForm',x->>'answerForm','trainingGoal','明确表达意图','promptZh','任务 '||(x->>'position')||'：'||case x->>'answerForm' when 'response' then '给朋友写一两句回复' when 'gap' then '只填指定空格' else '写完整词块' end,'promptEn','', 'expectedAnswers',jsonb_build_array(case when x->>'questionType'='collocation_gap' then 'as' else x->>'chunk' end),'acceptedVariants','[]'::jsonb,'semanticBoundary','PRIVATE target as / figured must never be public','gradingRubric','按要求的答案形式评分','hints','["一个语义线索"]'::jsonb,'learningCard',null) order by (x->>'position')::integer) from jsonb_array_elements(j.input_snapshot->'items')x)) from english_private.ai_jobs j where id=(select(v->>'jobId')::uuid from st where k='job');
select pg_temp.expect_error(format('select english_api.import_ai_result(%L,%L::jsonb)',(select v->>'jobId' from st where k='job'),(select jsonb_set(v,'{items,0,phase}','"expression"')::text from st where k='payload')),'QUESTION_PHASE_MISMATCH');
select pg_temp.expect_error(format('select english_api.import_ai_result(%L,%L::jsonb)',(select v->>'jobId' from st where k='job'),(select jsonb_set(v,'{items,2,promptEn}','"The train runs as _____."')::text from st where k='payload')),'QUESTION_LEAKS_TARGET');
select english_api.import_ai_result((select(v->>'jobId')::uuid from st where k='job'),(select v from st where k='payload'));
select pg_temp.assert_true((english_api.import_ai_result((select(v->>'jobId')::uuid from st where k='job'),(select v from st where k='payload'))->>'idempotent')::boolean,'lesson import idempotent');
update st set v=english_api.get_review_bootstrap() where k='boot';
select pg_temp.assert_true((select v->'lesson'->'material'='null'::jsonb from st where k='boot'),'material is not sent before review');
select pg_temp.assert_true(not exists(select 1 from jsonb_array_elements((select v->'questions' from st where k='boot'))q where q->'semanticBoundary'<>'null'::jsonb),'private scoring boundary absent');
select pg_temp.expect_error(format('select english_api.record_lesson_activity(%L,%L,0,null,%L)',(select v->'session'->>'id' from st where k='boot'),'reading_start','too-early'),'REVIEW_NOT_FINISHED');
select english_api.record_question_activity((select(v->'session'->>'id')::uuid from st where k='boot'),2,'hint','hint-test');
insert into st select 'answers',jsonb_agg(jsonb_build_object('position',q.position,'answer',case when q.position in (4,5) then '' else q.expected_answers->>0 end,'attemptState',case q.position when 4 then 'dont_know' when 5 then 'skipped' else 'answered' end,'revision',1,'revealHash','test-reveal','hintUsed',q.position=2,'hintCount',case when q.position=2 then 1 else 0 end,'learningCardViewed',false,'activeSeconds',20,'clientInstanceId','sql','pageStartedAt',now(),'practiceStartedAt',now()-interval '20 seconds','practiceEndedAt',now()) order by q.position) from english_private.questions q where q.metadata->>'phase'='review';
insert into english_private.review_events(owner_id,phrase_id,prompt,user_answer,result,question_type,affects_srs,rule_version,learning_date,target_outcome,hint_used) select owner_id,phrase_id,'prior v2','answer','normal','whole_recall',true,'english_v2',english_private.learning_date(),'correct',false from english_private.questions where position=6;
insert into english_private.lesson_exposures(owner_id,phrase_id,learning_date,source,created_at) select owner_id,phrase_id,english_private.learning_date(),'reading',now()-interval '1 hour' from english_private.questions where position=8;
select english_api.checkpoint_answers((select(v->'session'->>'id')::uuid from st where k='boot'),(select v from st where k='answers'),1,'checkpoint-review',english_private.sha256_json((select v from st where k='answers')));
select english_api.record_lesson_activity((select(v->'session'->>'id')::uuid from st where k='boot'),'reading_start',0,null,'read-start');
select pg_temp.assert_true((english_api.get_review_bootstrap()->'lesson'->'material'->>'title')='A short conversation','reading restores across clients');
update english_private.sessions set learning_date=learning_date-7;
update english_private.daily_queues set queue_date=queue_date-7;
select pg_temp.assert_true((english_api.get_review_bootstrap()->'session'->>'id')=(select v->'session'->>'id' from st where k='boot') and (english_api.get_review_bootstrap()->>'learningDate')=(english_private.learning_date()-7)::text,'cross-day bootstrap resumes the existing session');
select pg_temp.assert_true((select count(*)=8 from jsonb_array_elements(english_api.get_review_bootstrap()->'questions')q where q->'draft' is not null and q->'draft'<>'null'::jsonb),'all prior review checkpoints survive cross-day resumption');
update english_private.sessions set learning_date=learning_date+7;
update english_private.daily_queues set queue_date=queue_date+7;
select english_api.record_lesson_activity((select(v->'session'->>'id')::uuid from st where k='boot'),'reading_complete',75,null,'read-complete');
insert into st select 'expressions',jsonb_agg(jsonb_build_object('position',q.position,'answer',q.expected_answers->>0,'attemptState','answered','revision',1,'revealHash','test','hintUsed',false,'hintCount',0,'learningCardViewed',false,'activeSeconds',35,'clientInstanceId','sql','pageStartedAt',now(),'practiceEndedAt',now()) order by q.position) from english_private.questions q where q.metadata->>'phase'='expression';
select english_api.checkpoint_answers((select(v->'session'->>'id')::uuid from st where k='boot'),(select v from st where k='expressions'),2,'checkpoint-expression',english_private.sha256_json((select v from st where k='expressions')));
select pg_temp.assert_true((select bool_and((metadata->>'exposed')::boolean) from english_private.answer_drafts where metadata->>'phase'='expression'),'read expression exposure frozen server-side');
insert into st select 'frozen',to_jsonb(english_private.sha256_json(jsonb_agg(jsonb_build_object('position',position,'questionId',question_id,'answer',answer,'revision',revision,'answerHash',answer_hash) order by position))) from english_private.answer_drafts;
insert into st values('submission',english_api.submit_session((select(v->'session'->>'id')::uuid from st where k='boot'),'[]',3,'submit-v3',(select v#>>'{}' from st where k='frozen')));
select pg_temp.assert_true((select count(*)=9 from english_private.grade_requests),'skipped not sent for grading');
insert into st values('grade-job',english_api.create_ai_job('grade_submission',null,(select(v->>'submissionId')::uuid from st where k='submission'),'grade-v3'));
insert into st values('grade-prompt',english_api.get_ai_job_prompt((select(v->>'jobId')::uuid from st where k='grade-job')));
select pg_temp.assert_true((select jsonb_array_length(v->'outputContract'->'items')=9 and not (v->'outputContract' ? 'material') and not exists(select 1 from jsonb_array_elements(v->'snapshot'->'items')s left join jsonb_array_elements(v->'outputContract'->'items')x on x->'position'=s->'position' where x->'requestId' is distinct from s->'requestId' or x->'observedAnswer' is distinct from s->'observedAnswer' or x->'answerHash' is distinct from s->'answerHash' or x->'hintUsed' is distinct from s->'hintUsed' or (s->>'attemptState'='dont_know' and x->>'targetOutcome'<>'forgotten')) from st where k='grade-prompt'),'grading example covers only frozen requests and preserves unknown/hint evidence');
insert into st select 'grades',jsonb_build_object('jobId',j.id,'batchId',j.batch_id,'snapshotHash',j.snapshot_hash,'ruleVersion','english_v3','modelId','test','items',(select jsonb_agg(jsonb_build_object('requestId',x->>'requestId','position',x->'position','observedAnswer',x->>'observedAnswer','answerHash',x->>'answerHash','result','normal','targetOutcome',case when x->>'attemptState'='dont_know' then 'forgotten' when x->>'position'='7' then 'not_measured' else 'correct' end,'meaningOk',true,'naturalness','natural','hintUsed',x->'hintUsed','confidence',0.9,'feedbackZh','一处反馈和自然示例','evidence','实际作答','expectedAnswer','A natural answer.','extraPractice','[]'::jsonb) order by (x->>'position')::integer) from jsonb_array_elements(j.input_snapshot->'items')x)) from english_private.ai_jobs j where id=(select(v->>'jobId')::uuid from st where k='grade-job');
select english_api.import_ai_result((select(v->>'jobId')::uuid from st where k='grade-job'),(select v from st where k='grades'));
insert into st select 'decisions',jsonb_agg(jsonb_build_object('position',position,'decision','accept') order by position) from english_private.grade_results;
select english_api.confirm_grades((select(v->>'submissionId')::uuid from st where k='submission'),(select v from st where k='decisions'),2,'confirm-v3',english_private.sha256_json((select v from st where k='decisions')));
select pg_temp.assert_true((select count(*)=9 from english_private.review_events where grade_result_id is not null),'exactly attempted events');
select pg_temp.assert_true(not exists(select 1 from english_private.review_events where metadata->>'phase'='expression' and affects_srs),'post-reading never advances');
select pg_temp.assert_true((select p.review_stage=3 from english_private.phrases p join english_private.questions q on q.phrase_id=p.id where q.question_type='collocation_gap' limit 1),'gap correct holds stage');
select pg_temp.assert_true((select p.review_stage=3 from english_private.phrases p join english_private.questions q on q.phrase_id=p.id where q.position=2),'hinted correct holds stage');
select pg_temp.assert_true((select p.review_stage=3 from english_private.phrases p join english_private.questions q on q.phrase_id=p.id where q.position=5),'skipped preserves stage');
select pg_temp.assert_true((select p.review_stage=0 from english_private.phrases p join english_private.questions q on q.phrase_id=p.id where q.position=4),'dont know resets stage');
select pg_temp.assert_true((select bool_and(p.review_stage=3) from english_private.phrases p join english_private.questions q on q.phrase_id=p.id where q.position in (6,8)),'same-day v2 and exposure block promotion');
select pg_temp.assert_true((english_api.get_dashboard()->'v3'->>'completedLessons')='1','completed lesson report');
select pg_temp.assert_true((english_api.get_submission_status((select(v->>'submissionId')::uuid from st where k='submission'))->'lessonSummary'->>'skipped')='1','partial completion summary');
select pg_temp.assert_true((english_api.get_review_bootstrap()->>'state')='committed','no duplicate same-day lesson');
select english_api.confirm_grades((select(v->>'submissionId')::uuid from st where k='submission'),(select v from st where k='decisions'),2,'confirm-v3',english_private.sha256_json((select v from st where k='decisions')));
select pg_temp.assert_true((select count(*)=9 from english_private.review_events where grade_result_id is not null),'retry does not double count');
select english_api.set_learning_settings(6,0,'settings-v3');
select pg_temp.assert_true((english_api.get_review_bootstrap()->'settings'->>'defaultQuestionCount')='6','future setting only');
select pg_temp.assert_true((select count(*)=10 from english_private.questions),'existing lesson immutable');
set local role authenticated;
select pg_temp.expect_error('select * from english_private.lessons','permission denied');
select set_config('request.jwt.claim.sub','e5555555-5555-4555-8555-555555555555',true);
select pg_temp.expect_error('select english_api.get_review_bootstrap()','OWNER_REQUIRED');
reset role;
rollback;
