-- Read-only summary; the Python reconciler additionally verifies every raw hash and target ID.
-- psql -v owner_id=<actual-auth-uuid> -v batch_id=<manifest-batch-uuid> -f this-file
\set ON_ERROR_STOP on
begin read only;
with batch as (
 select * from english_private.import_batches
 where owner_id=:'owner_id'::uuid and id=:'batch_id'::uuid
), actual as (
 select jsonb_build_object('english_private.answer_draft_history',(select count(*) from english_private.answer_draft_history where owner_id=:'owner_id'::uuid),'english_private.answer_drafts',(select count(*) from english_private.answer_drafts where owner_id=:'owner_id'::uuid),'english_private.candidate_generation_rows',(select count(*) from english_private.candidate_generation_rows where owner_id=:'owner_id'::uuid),'english_private.candidates',(select count(*) from english_private.candidates where owner_id=:'owner_id'::uuid),'english_private.commit_journal',(select count(*) from english_private.commit_journal where owner_id=:'owner_id'::uuid),'english_private.context_candidates',(select count(*) from english_private.context_candidates where owner_id=:'owner_id'::uuid),'english_private.contexts',(select count(*) from english_private.contexts where owner_id=:'owner_id'::uuid),'english_private.daily_queue_items',(select count(*) from english_private.daily_queue_items where owner_id=:'owner_id'::uuid),'english_private.daily_queues',(select count(*) from english_private.daily_queues where owner_id=:'owner_id'::uuid),'english_private.error_events',(select count(*) from english_private.error_events where owner_id=:'owner_id'::uuid),'english_private.grade_requests',(select count(*) from english_private.grade_requests where owner_id=:'owner_id'::uuid),'english_private.grade_result_attempts',(select count(*) from english_private.grade_result_attempts where owner_id=:'owner_id'::uuid),'english_private.import_rows',(select count(*) from english_private.import_rows where owner_id=:'owner_id'::uuid),'english_private.legacy_recovery',(select count(*) from english_private.legacy_recovery where owner_id=:'owner_id'::uuid),'english_private.phrases',(select count(*) from english_private.phrases where owner_id=:'owner_id'::uuid),'english_private.question_attempts',(select count(*) from english_private.question_attempts where owner_id=:'owner_id'::uuid),'english_private.questions',(select count(*) from english_private.questions where owner_id=:'owner_id'::uuid),'english_private.review_events',(select count(*) from english_private.review_events where owner_id=:'owner_id'::uuid),'english_private.sessions',(select count(*) from english_private.sessions where owner_id=:'owner_id'::uuid),'english_private.settings',(select count(*) from english_private.settings where owner_id=:'owner_id'::uuid),'english_private.source_notes',(select count(*) from english_private.source_notes where owner_id=:'owner_id'::uuid),'english_private.submissions',(select count(*) from english_private.submissions where owner_id=:'owner_id'::uuid)) counts
), sheets as (
 select coalesce(jsonb_object_agg(e.key,coalesce(x.n,0)),'{}'::jsonb) counts from batch b cross join lateral jsonb_each(b.reconciliation->'sheetCounts') e left join (
  select source_sheet,count(*) n from english_private.import_rows
  where owner_id=:'owner_id'::uuid and import_batch_id=:'batch_id'::uuid group by source_sheet
 ) x on x.source_sheet=e.key
)
select jsonb_build_object('ok',coalesce((select status='promoted' and expected_row_count=(select count(*) from english_private.import_rows where owner_id=:'owner_id'::uuid and import_batch_id=:'batch_id'::uuid) and expected_formula_count=(select coalesce(sum(jsonb_array_length(formula_cells)),0) from english_private.import_rows where owner_id=:'owner_id'::uuid and import_batch_id=:'batch_id'::uuid) and reconciliation->'tableCounts'=actual.counts and reconciliation->'sheetCounts'=sheets.counts from batch),false),'batchId',:'batch_id','actualCounts',actual.counts,'sheetCounts',sheets.counts) from actual,sheets;
rollback;
