import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { LessonView } from "./LessonView";
import type { ApiClient, ReviewBootstrap } from "../lib/contracts";
vi.mock("../lib/recovery",()=>({loadRecovery:vi.fn().mockResolvedValue(null),saveRecovery:vi.fn().mockResolvedValue(undefined)}));
import { loadRecovery, saveRecovery } from "../lib/recovery";
const q=(position:number,phase:"review"|"expression"="review")=>({id:`q${position}`,position,phase,answerForm:"chunk" as const,phraseId:`p${position}`,candidateId:null,questionType:"whole_recall",promptZh:`任务 ${position}`,promptEn:null,expectedAnswers:["run as scheduled"],acceptedVariants:[],semanticBoundary:"private answer leak",contentHash:"hash",draft:null,hints:["提示线索"],isNew:false});
const b=():ReviewBootstrap=>({ok:true,ruleVersion:"english_v3",state:"open",learningDate:"2026-09-28",session:{id:"s",revision:1,maxQuestions:3,status:"open"},questions:[q(1),q(2,"expression"),q(3,"expression")],lesson:{id:"l",theme:"life",sequence:1,material:null,readingStarted:false,readingCompleted:false,readingSeconds:0,burden:null}});
function setup(bootstrap=b()) {let revision=1;const api={checkpointAnswers:vi.fn(async()=>({ok:true,revision:++revision})),recordLessonActivity:vi.fn().mockResolvedValue({ok:true}),recordQuestionActivity:vi.fn().mockResolvedValue({ok:true}),getReviewBootstrap:vi.fn().mockResolvedValue({...bootstrap,lesson:{...bootstrap.lesson,readingStarted:true,material:{title:"Story",body:"Safe reading text",notes:[],explanationZh:"帮助"}}}),submitSession:vi.fn().mockResolvedValue({submissionId:"sub"})} as unknown as ApiClient;const onSubmitted=vi.fn();render(<LessonView api={api} bootstrap={bootstrap} onRefresh={vi.fn().mockResolvedValue(undefined)} onSubmitted={onSubmitted}/>);return {api,onSubmitted};}
afterEach(cleanup);
beforeEach(()=>{vi.clearAllMocks();vi.mocked(loadRecovery).mockResolvedValue(null);});
describe("lesson phases and evidence",()=>{
 it("keeps private rubric and material hidden until review is saved",async()=>{const {api}=setup();await screen.findByText("任务 1");expect(screen.queryByText("private answer leak")).toBeNull();expect(screen.queryByText("Story")).toBeNull();fireEvent.click(screen.getByText("跳过"));await screen.findByText("开始阅读");fireEvent.click(screen.getByText("开始阅读"));await screen.findByText("Story");expect(api.checkpointAnswers).toHaveBeenCalled();expect(api.recordLessonActivity).toHaveBeenCalledWith("s","reading_start",0,null,"lesson:s:reading_start:0");});
 it("freezes dont_know separately from skipped and submits a partial lesson",async()=>{const {api}=setup();await screen.findByText("任务 1");fireEvent.click(screen.getByText("暂时不会"));await screen.findByText("参考表达");fireEvent.click(screen.getByText("结束本次并批改已答内容"));await waitFor(()=>expect(api.submitSession).toHaveBeenCalled());const batch=vi.mocked(api.checkpointAnswers).mock.calls.flatMap(call=>call[0].answers);expect(batch.map(a=>a.attemptState)).toEqual(["dont_know","skipped","skipped"]);expect(batch.map(a=>a.answer)).toEqual(["","",""]);});
 it("persists unrevealed text and restores it",async()=>{vi.mocked(loadRecovery).mockResolvedValue({sessionId:"s",sessionRevision:1,answers:[],checkpointedPositions:[],updatedAt:"now",lessonWork:{inputs:{1:"my draft"},seconds:{1:12}}});setup();await screen.findByDisplayValue("my draft");fireEvent.change(screen.getByRole("textbox"),{target:{value:"changed draft"}});await waitFor(()=>expect(saveRecovery).toHaveBeenCalledWith(expect.objectContaining({lessonWork:expect.objectContaining({inputs:{1:"changed draft"}})})));});
 it("does not treat a hidden learning card as independent prior knowledge",async()=>{const boot=b();boot.questions[0]={...boot.questions[0],isNew:true,learningCard:{meaningZh:"按计划运行",example:"The task ran as scheduled.",usageNote:"按安排"}};setup(boot);await screen.findByText("先熟悉这个表达");expect(screen.queryByRole("textbox")).toBeNull();fireEvent.click(screen.getByText("隐藏学习卡，试着回忆"));await screen.findByRole("textbox");});
 it("preserves conflicting local and cloud answers until explicitly resolved",async()=>{const boot=b();boot.questions[0]={...boot.questions[0],draft:{answer:"cloud answer",revision:1,answerHash:"hash",status:"checkpointed",attemptState:"answered",activeSeconds:8}};vi.mocked(loadRecovery).mockResolvedValue({sessionId:"s",sessionRevision:1,answers:[{position:1,answer:"local answer",revision:1,revealHash:"hash",attemptState:"answered",activeSeconds:7,clientInstanceId:"test",pageStartedAt:"now"}],checkpointedPositions:[],updatedAt:"now"});setup(boot);await screen.findByText("请先核对不同设备的答案");expect(screen.getByText(/local answer/)).toBeTruthy();expect(screen.getByText(/cloud answer/)).toBeTruthy();expect(saveRecovery).not.toHaveBeenCalled();fireEvent.click(screen.getByText("已核对，继续云端进度"));await screen.findByText("开始阅读");});

});
