import { type FormEvent, useCallback, useEffect, useState } from "react";
import type { ApiClient, CandidateBootstrap, CandidateItem, ContextInbox, PhraseDetail, PhraseLibrary } from "../lib/contracts";
import { makeIdempotencyKey } from "../lib/hash";
import { AiJobPanel } from "./AiJobPanel";

export function PhraseView({client}: {client:ApiClient}) {
  const [search,setSearch]=useState("");const [data,setData]=useState<PhraseLibrary|null>(null);const [detail,setDetail]=useState<PhraseDetail|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  async function load(offset=0){setBusy(true);setError(null);try{const next=await client.getPhraseLibrary(search||null,100,offset);setData(current=>offset?{...next,items:[...(current?.items??[]),...next.items]}:next);}catch(caught){setError(caught instanceof Error?caught.message:"搭配加载失败。");}finally{setBusy(false);}}
  useEffect(()=>{void load();},[client]);
  async function open(id:string){setBusy(true);try{setDetail(await client.getPhraseDetail(id));}catch(caught){setError(caught instanceof Error?caught.message:"详情加载失败。");}finally{setBusy(false);}}
  if(detail)return <main className="section-content"><button className="quiet-button" onClick={()=>setDetail(null)}>← 返回搭配库</button><section className="section-intro"><h1>{detail.phrase.chunk}</h1><p>{detail.phrase.cueZh}</p></section><section className="glass-card"><p>{detail.phrase.naturalExample}</p>{detail.phrase.commonMistake&&<p>常见问题：{detail.phrase.commonMistake}</p>}{detail.phrase.notes&&<p>{detail.phrase.notes}</p>}<p>复习阶段 {detail.phrase.reviewStage} · 下次复习 {detail.phrase.nextReviewAt?new Date(detail.phrase.nextReviewAt).toLocaleDateString("zh-CN"):"待安排"}</p><h2>练习历史</h2>{detail.history.length?detail.history.map((item,index)=><article className="history-item" key={`${item.reviewedAt}:${index}`}><p>{new Date(item.reviewedAt).toLocaleString("zh-CN")} · {item.result}</p><p>{item.prompt}</p><p>你的答案：{item.userAnswer??"无记录"}</p><p>参考：{item.expectedAnswer??"无记录"}</p></article>):<p>暂无练习历史。</p>}</section></main>;
  return <main className="section-content"><section className="section-intro"><h1>我的搭配</h1><p>查看表达用法、复习安排和真实作答记录。</p></section><form className="search-bar" onSubmit={event=>{event.preventDefault();void load();}}><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="搜索搭配、中文提示或主题"/><button disabled={busy}>{busy?"搜索中…":"搜索"}</button></form>{error&&<p role="alert">{error}</p>}<div className="library-list">{data?.items.map(item=><article key={item.id}><button className="phrase-open" onClick={()=>void open(item.id)} disabled={busy}><h2>{item.chunk}</h2><p>{item.cueZh}</p></button><span className="stage-badge">阶段 {item.reviewStage}</span><dl><div><dt>练习次数</dt><dd>{item.timesSeen}</dd></div><div><dt>下次复习</dt><dd>{item.nextReviewAt?new Date(item.nextReviewAt).toLocaleDateString("zh-CN"):"待安排"}</dd></div></dl></article>)}</div>{data?.items.length===0&&<p>尚无匹配的搭配。</p>}{data&&data.items.length>0&&data.items.length%100===0&&<button className="secondary-button" onClick={()=>void load(data.items.length)} disabled={busy}>加载更多</button>}</main>;
}

export function ContextView({client}: {client:ApiClient}) {
  const [data,setData]=useState<ContextInbox|null>(null);const [rawText,setRawText]=useState("");const [note,setNote]=useState("");const [sourceUrl,setSourceUrl]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const [selected,setSelected]=useState<string|null>(null);
  const refresh=useCallback(async()=>{try{setData(await client.getContextInbox());}catch(caught){setMessage(caught instanceof Error?caught.message:"语料读取失败。");}},[client]);
  useEffect(()=>{void refresh();},[refresh]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setMessage(null);try{await client.saveContext({rawText:rawText.trim(),userNote:note.trim(),sourceUrl:sourceUrl.trim()||null,selectedSpans:[]},null,makeIdempotencyKey("context"));setRawText("");setNote("");setSourceUrl("");await refresh();setMessage("语料已保存。选择整理语料后，可以用 ChatGPT 提取候选。");}catch(caught){setMessage(caught instanceof Error?caught.message:"保存失败。");}finally{setBusy(false);}}
  async function decide(id:string,action:"accept"|"edit"|"reject",edited:string|null){setBusy(true);try{await client.decideContextCandidate(id,action,edited,makeIdempotencyKey(`context-candidate:${id}`));await refresh();}catch(caught){setMessage(caught instanceof Error?caught.message:"处理失败。");}finally{setBusy(false);}}
  return <main className="section-content"><section className="section-intro"><h1>把真实语境留下来</h1><p>留下工作、生活和阅读中你真正想用的表达。</p></section><div className="page-stack"><form className="glass-card context-form" onSubmit={submit}><label>原文<textarea value={rawText} onChange={event=>setRawText(event.target.value)} required/></label><label>来源链接（可选）<input type="url" value={sourceUrl} onChange={event=>setSourceUrl(event.target.value)}/></label><label>想表达什么（可选）<input value={note} onChange={event=>setNote(event.target.value)}/></label><button className="primary-button" disabled={busy||!rawText.trim()}>保存语料</button></form>{message&&<p role="status">{message}</p>}{data?.contexts.map(context=><article key={context.id} className="glass-card"><blockquote>{context.rawText}</blockquote><p>{context.userNote}</p>{context.sourceUrl&&<a href={context.sourceUrl} target="_blank" rel="noreferrer">查看原文</a>}<button className="secondary-button" onClick={()=>setSelected(selected===context.id?null:context.id)}>整理这段语料</button>{selected===context.id&&<AiJobPanel api={client} kind="context_extract" subjectId={context.id} onImported={refresh}/>}<div className="candidate-list">{context.candidates.map(candidate=><CandidateEditor key={candidate.id} item={{id:candidate.id,source:"context",candidate:candidate.candidate,cueZh:candidate.cueZh,whyUseful:candidate.whyUseful,naturalExample:null,status:candidate.decisionStatus}} busy={busy} decide={(action,edited)=>decide(candidate.id,action,edited??null)}/>)}</div></article>)}</div></main>;
}
export function CandidateView({client}: {client:ApiClient}) {
  const [data,setData]=useState<CandidateBootstrap|null>(null);const [message,setMessage]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [count,setCount]=useState(2);
  const refresh=useCallback(async()=>{try{setData(await client.getCandidateBootstrap());}catch(caught){setMessage(caught instanceof Error?caught.message:"候选读取失败。");}},[client]);useEffect(()=>{void refresh();},[refresh]);
  async function decide(item:CandidateItem,action:"accept"|"edit"|"reject",editedCandidate?:string){setBusy(true);try{await client.confirmCandidates([{id:item.id,source:item.source,action,editedCandidate}],makeIdempotencyKey(`candidate:${item.id}`));await refresh();}catch(caught){setMessage(caught instanceof Error?caught.message:"处理失败。");}finally{setBusy(false);}}
  return <main className="section-content"><section className="section-intro"><h1>确认学习候选</h1><p>新表达经你确认后，再按每日最多 2 项的规则进入学习。</p>{data&&<p>已确认、等待安排：{data.readyCount} 项</p>}</section><div className="page-stack"><section className="glass-card"><label>希望补充的候选数<input type="number" min={1} max={20} step={1} value={count} onChange={event=>setCount(Math.max(1,Math.min(20,Math.round(Number(event.target.value)))))}/></label><AiJobPanel api={client} kind="candidate_generate" requestedCount={count} onImported={refresh}/></section>{message&&<p role="status">{message}</p>}{data?.items.map(item=><CandidateEditor key={item.id} item={item} busy={busy} decide={(action,edited)=>decide(item,action,edited)}/>)}{data?.items.length===0&&<p>目前没有待确认候选。优先添加你自己的语料，也可以请求补充。</p>}</div></main>;
}
function CandidateEditor({item,busy,decide}: {item:CandidateItem;busy:boolean;decide(action:"accept"|"edit"|"reject",edited?:string):Promise<void>}) {
  const [editing,setEditing]=useState(false);const [edited,setEdited]=useState(item.candidate);const pending=["staged","pending","proposed","ready","generated","unreviewed"].includes(item.status);
  return <article className="glass-card candidate-editor"><h3>{item.candidate}</h3><p>{item.cueZh}</p><p>{item.whyUseful}</p>{item.naturalExample&&<blockquote>{item.naturalExample}</blockquote>}{pending?<>{editing&&<label>修改表达<input value={edited} onChange={event=>setEdited(event.target.value)}/></label>}<div className="button-row"><button className="primary-button" disabled={busy||!edited.trim()} onClick={()=>void decide(editing?"edit":"accept",editing?edited.trim():undefined)}>{editing?"保存修改并接受":"接受"}</button><button className="secondary-button" disabled={busy} onClick={()=>setEditing(!editing)}>{editing?"取消编辑":"编辑"}</button><button className="quiet-button" disabled={busy} onClick={()=>void decide("reject")}>拒绝</button></div></>:<span className="stage-badge">{item.status}</span>}</article>;
}
